import '../core/feather_codec.dart';

/// ════════════════════════════════════════════════════════════
/// Yardflare Rally — encoded configuration surface.
/// ════════════════════════════════════════════════════════════
///
/// Every URL / key that the gray flow needs at runtime lives here as
/// obfuscated byte arrays (never plaintext strings). To rotate any value:
///   1. Edit the plaintext in `tool/encode_era_values.dart`.
///   2. If you want a stronger fingerprint rotation, change the salt AND
///      the algorithm in `lib/hatchway/core/feather_codec.dart` (kept in
///      sync with the tool).
///   3. Run `dart run tool/encode_era_values.dart` — the VERIFY line at the
///      end MUST print. Paste the printed arrays below verbatim.
///
/// The gray gate stays disabled (native game only) until `endpoint`,
/// `appsFlyerKey` and `firebaseProjectNumber` are all non-empty.
abstract final class LanternRallyEnv {
  static const String appTitle = 'Yardflare Rally';
  static const String bundleId = 'com.yardflare.rallygame';

  /// iOS App Store numeric id (used for GCD lookup + config `store_id`).
  static const String iosStoreId = '6792709646';

  static const int pushSnoozeSeconds = 259200; // 3 days
  static const int organicRecheckSeconds = 6;

  // ── Encoded secrets (regenerated by tool/encode_era_values.dart) ─────
  // endpoint — https://yardflarerally.com/config.php
  static const List<int> _endpoint = <int>[
    42, 29, 171, 162, 159, 163, 213, 33, 56, 35, 57, 73, 105, 63, 77, 207,
    195, 234, 228, 224, 241, 147, 11, 130, 155, 73, 61, 70, 168, 163, 65,
    53, 5, 51, 23, 37, 69,
  ];
  // privacy — https://yardflarerally.com/privacy-policy.html
  static const List<int> _privacy = <int>[
    42, 29, 171, 162, 159, 163, 213, 33, 56, 35, 57, 73, 105, 63, 77, 207,
    195, 234, 228, 224, 241, 147, 11, 130, 155, 73, 61, 222, 146, 191, 64,
    52, 7, 70, 98, 41, 123, 153, 20, 225, 44, 116, 114, 178, 19, 15,
  ];
  // support — https://yardflarerally.com/support.html
  static const List<int> _support = <int>[
    42, 29, 171, 162, 159, 163, 213, 33, 56, 35, 57, 73, 105, 63, 77, 207,
    195, 234, 228, 224, 241, 147, 11, 130, 155, 73, 61, 198, 156, 219, 32,
    245, 143, 150, 110, 37, 77, 25, 60,
  ];
  // AppsFlyer GCD base — https://gcdsdk.appsflyer.com/install_data/v5.0/
  static const List<int> _gcd = <int>[
    42, 29, 171, 162, 159, 163, 213, 33, 200, 163, 137, 103, 97, 79, 164, 70,
    146, 226, 237, 244, 241, 147, 191, 198, 218, 57, 45, 54, 40, 191, 193,
    118, 140, 199, 103, 39, 27, 157, 84, 144, 42, 117, 130, 226, 9, 183, 77,
  ];
  // User-Agent version fragments — bumped from previous project.
  static const List<int> _webkit = <int>[
    83, 63, 41, 141, 141, 226, 82, 59,
  ];
  static const List<int> _safari = <int>[79, 59, 31, 129];
  static const List<int> _safariTail = <int>[83, 63, 43, 141, 141];
  // AppsFlyer Dev Key
  static const List<int> _appsFlyerKey = <int>[
    226, 61, 179, 59, 94, 100, 199, 72, 225, 101, 9, 105, 233, 237, 111, 77,
    2, 42, 115, 74, 227, 114,
  ];
  // Firebase project number (GCM_SENDER_ID)
  static const List<int> _firebaseProject = <int>[
    87, 189, 51, 0, 133, 115, 146, 61, 74, 118, 59, 233,
  ];
  // OneLink is OPTIONAL — never part of the gate-enable predicate.
  static const List<int> _oneLinkHost = <int>[
    110, 151, 167, 168, 55, 198, 70, 124, 216, 231, 161, 89, 65, 110, 164,
    65, 115, 182, 98, 234, 240, 3, 11, 1, 145,
  ];

  static String get endpoint => openLantern(_endpoint);
  static String get privacyUrl => openLantern(_privacy);
  static String get supportUrl => openLantern(_support);
  static String get gcdBase => openLantern(_gcd);
  static String get webKitVersion => openLantern(_webkit);
  static String get safariVersion => openLantern(_safari);
  static String get safariTail => openLantern(_safariTail);
  static String get appsFlyerKey => openLantern(_appsFlyerKey);
  static String get firebaseProjectNumber => openLantern(_firebaseProject);
  static String get oneLinkHost => openLantern(_oneLinkHost);

  static String get storeToken => 'id$iosStoreId';

  /// Gate needs config endpoint + AF key + Firebase project number ONLY.
  /// ⚠️ Never add optional fields (OneLink etc.) here — a missing optional
  /// would silently disable the whole gray flow.
  static bool get grayCredentialsReady =>
      endpoint.isNotEmpty &&
      appsFlyerKey.isNotEmpty &&
      firebaseProjectNumber.isNotEmpty;
}
