import '../core/feather_codec.dart';

/// ════════════════════════════════════════════════════════════
/// ⚠️  TEMPLATE — fill every credential before shipping.
/// ════════════════════════════════════════════════════════════
///
/// All secrets are stored as obfuscated byte arrays (never plaintext):
///   1. Put your plaintext values into tool/encode_era_values.dart.
///   2. Change the cipher salt in lib/hatchway/core/feather_codec.dart
///      (`_nestSalt`) to something unique for THIS app.
///   3. Run `dart run tool/encode_era_values.dart`.
///   4. Paste the printed byte arrays below. The VERIFY block must
///      round-trip EXACTLY (a stray/missing byte silently corrupts the
///      URL — that bug cost real debugging time; always re-verify).
///
/// The gray gate stays disabled (white part only) until `endpoint`,
/// `appsFlyerKey` and `firebaseProjectNumber` are all non-empty.
abstract final class EraHatchConfig {
  static const String appTitle = 'Yardflare Rally';
  static const String bundleId = 'com.yardflare.rallygame';

  /// iOS App Store numeric id (used for GCD + store_id).
  static const String iosStoreId = '6792709646';

  static const int pushSnoozeSeconds = 259200; // 3 days
  static const int organicRecheckSeconds = 6;

  // ── Encoded secrets (generated by tool/encode_era_values.dart) ────────
  static const List<int> _endpoint = <int>[
    71, 228, 18, 38, 55, 183, 0, 251, 243, 45, 180, 120, 165, 239, 21, 95, 13,
    73, 36, 130, 187, 236, 116, 80, 248, 45, 229, 35, 43, 133, 143, 127, 248,
    124, 159, 247, 34,
  ];
  static const List<int> _privacy = <int>[
    71, 228, 18, 38, 55, 183, 0, 251, 243, 45, 180, 120, 165, 239, 21, 95, 13,
    73, 36, 130, 187, 236, 116, 80, 248, 45, 229, 48, 46, 128, 159, 119, 244,
    199, 92, 255, 33, 237, 190, 79, 119, 7, 133, 103, 235, 134,
  ];
  static const List<int> _support = <int>[
    71, 228, 18, 38, 55, 183, 0, 251, 243, 45, 180, 120, 165, 239, 21, 95, 13,
    73, 36, 130, 187, 236, 116, 80, 248, 45, 229, 51, 49, 135, 153, 133, 3,
    194, 93, 247, 38, 238, 193,
  ];
  static const List<int> _appsFlyerKey = <int>[
    57, 164, 22, 249, 15, 195, 56, 18, 188, 68, 182, 136, 133, 196, 36, 100,
    33, 25, 17, 79, 151, 184,
  ];
  static const List<int> _firebaseProject = <int>[
    22, 165, 214, 235, 244, 180, 3, 255, 177, 0, 116, 72,
  ];

  // AppsFlyer GCD base.
  static const List<int> _gcd = <int>[
    71, 228, 18, 38, 55, 183, 0, 251, 225, 47, 166, 135, 163, 238, 226, 78, 24,
    71, 54, 124, 187, 236, 171, 95, 183, 35, 37, 45, 235, 128, 151, 137, 5,
    175, 155, 251, 17, 229, 182, 96, 95, 8, 147, 40, 172, 74, 50,
  ];

  // User-Agent version fragments.
  static const List<int> _webkit = <int>[21, 160, 211, 228, 245, 171, 2, 1];
  static const List<int> _safari = <int>[16, 168, 204, 235];
  static const List<int> _safariTail = <int>[21, 160, 210, 228, 245];

  // OneLink is OPTIONAL — it must NEVER be part of the gate-enable check.
  static const List<int> _oneLinkHost = <int>[
    88, 209, 16, 26, 42, 233, 50, 62, 223, 62, 163, 128, 171, 252, 226, 92, 22,
    60, 47, 127, 189, 222, 116, 90, 238,
  ];

  static String get endpoint => unfoldFeathers(_endpoint);
  static String get privacyUrl => unfoldFeathers(_privacy);
  static String get supportUrl => unfoldFeathers(_support);
  static String get gcdBase => unfoldFeathers(_gcd);
  static String get webKitVersion => unfoldFeathers(_webkit);
  static String get safariVersion => unfoldFeathers(_safari);
  static String get safariTail => unfoldFeathers(_safariTail);
  static String get appsFlyerKey => unfoldFeathers(_appsFlyerKey);
  static String get firebaseProjectNumber => unfoldFeathers(_firebaseProject);
  static String get oneLinkHost => unfoldFeathers(_oneLinkHost);

  static String get storeToken => 'id$iosStoreId';

  /// Gate needs config endpoint + AF key + Firebase project number.
  /// ⚠️ Do NOT add optional fields (e.g. OneLink) here — a missing optional
  /// value would silently disable the whole gray flow.
  static bool get grayCredentialsReady =>
      endpoint.isNotEmpty &&
      appsFlyerKey.isNotEmpty &&
      firebaseProjectNumber.isNotEmpty;
}
